# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b902ab3445be155c32434847202b7093fa9db22cf0db39edabe836e8f9da46773a85c2496ae46cc86c59fa7fdc208bd46c5c931059c60dd3d6beddbff7aa0939

test:
  secret_key_base: e7fabbcc28a5630d7820caf3ca8db0bbed7d458f863e6a90044fde45293e99c43a9267eaf3aba609c5517f4e0fd5eb87739b98263b52d859241f2f2567faa8d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
